// ========================================
// EGYPT TIME-TRAVEL TOURISM
// Sample Data for Tours, Destinations & Packages
// ========================================

export const destinations = [
    {
        id: 1,
        name: "Giza Pyramids",
        nameAr: "أهرامات الجيزة",
        tagline: "Where Time Began",
        description: "Stand before the last surviving Wonder of the Ancient World. The Great Pyramid has guarded the secrets of the pharaohs for 4,500 years.",
        era: "ancient",
        region: "Cairo",
        image: "/images/destinations/giza.jpg",
        highlights: ["Great Pyramid of Khufu", "Sphinx", "Sound & Light Show", "Camel Rides"],
        rating: 4.9,
        reviews: 12847,
        coordinates: { lat: 29.9792, lng: 31.1342 },
    },
    {
        id: 2,
        name: "Luxor Temple",
        nameAr: "معبد الأقصر",
        tagline: "The World's Greatest Open-Air Museum",
        description: "Walk through millennia of history in the ancient city of Thebes. Colossal statues and hieroglyph-covered walls tell stories of gods and kings.",
        era: "ancient",
        region: "Luxor",
        image: "/images/destinations/luxor.jpg",
        highlights: ["Valley of the Kings", "Karnak Temple", "Hot Air Balloons", "Nile Cruises"],
        rating: 4.8,
        reviews: 8932,
        coordinates: { lat: 25.6994, lng: 32.6421 },
    },
    {
        id: 3,
        name: "Abu Simbel",
        nameAr: "أبو سمبل",
        tagline: "Carved by Gods, Moved by Men",
        description: "Witness the colossal temples of Ramesses II, saved from the rising waters and relocated stone by stone in humanity's greatest archaeological rescue.",
        era: "ancient",
        region: "Aswan",
        image: "/images/destinations/abusimbel.jpg",
        highlights: ["Sun Festival", "Giant Statues", "Lake Nasser", "Nubian Villages"],
        rating: 4.9,
        reviews: 5621,
        coordinates: { lat: 22.3372, lng: 31.6258 },
    },
    {
        id: 4,
        name: "Alexandria",
        nameAr: "الإسكندرية",
        tagline: "Where East Meets West",
        description: "Founded by Alexander the Great, this Mediterranean jewel blends Greek, Roman, and Egyptian heritage with modern coastal charm.",
        era: "hellenistic",
        region: "Alexandria",
        image: "/images/destinations/alexandria.jpg",
        highlights: ["Bibliotheca Alexandrina", "Citadel of Qaitbay", "Catacombs", "Corniche"],
        rating: 4.6,
        reviews: 6234,
        coordinates: { lat: 31.2001, lng: 29.9187 },
    },
    {
        id: 5,
        name: "Siwa Oasis",
        nameAr: "واحة سيوة",
        tagline: "Desert Paradise",
        description: "An otherworldly escape where ancient Berber traditions meet salt lakes, date palms, and the mystical Oracle Temple of Amun.",
        era: "mixed",
        region: "Western Desert",
        image: "/images/destinations/siwa.jpg",
        highlights: ["Oracle Temple", "Cleopatra's Pool", "Salt Lakes", "Desert Safari"],
        rating: 4.7,
        reviews: 2187,
        coordinates: { lat: 29.2032, lng: 25.5195 },
    },
    {
        id: 6,
        name: "Red Sea Riviera",
        nameAr: "ريفييرا البحر الأحمر",
        tagline: "Underwater Kingdom",
        description: "Dive into crystal-clear waters teeming with vibrant coral reefs and exotic marine life. Sun, sea, and adventure await.",
        era: "modern",
        region: "Red Sea",
        image: "/images/destinations/redsea.jpg",
        highlights: ["Scuba Diving", "Snorkeling", "Beach Resorts", "Desert Excursions"],
        rating: 4.8,
        reviews: 15432,
        coordinates: { lat: 27.2579, lng: 33.8116 },
    },
];

export const tours = [
    {
        id: 1,
        title: "Pharaoh's Legacy",
        subtitle: "The Ultimate Egyptian Odyssey",
        days: 10,
        nights: 9,
        price: 3999,
        originalPrice: 4599,
        currency: "EUR",
        level: "Royal",
        category: "signature",
        description: "Experience Egypt like royalty. From private pyramid access to luxury Nile cruises, this is the definitive journey through time.",
        image: "/images/tours/pharaoh-legacy.jpg",
        timeline: [
            { day: 1, title: "Arrival in Cairo", description: "VIP airport transfer, check-in at Four Seasons at Nile Plaza" },
            { day: 2, title: "Pyramids of Giza", description: "Private sunrise access to the Great Pyramid, Sphinx encounter" },
            { day: 3, title: "Egyptian Museum", description: "Private tour of Tutankhamun's treasures, Old Cairo exploration" },
            { day: 4, title: "Fly to Luxor", description: "Private charter flight, Karnak Temple at sunset" },
            { day: 5, title: "Valley of the Kings", description: "Access to all tombs including Tutankhamun, Hatshepsut Temple" },
            { day: 6, title: "Nile Cruise Begins", description: "Board luxury dahabiya, sail to Edfu" },
            { day: 7, title: "Edfu & Kom Ombo", description: "Temple explorations, onboard fine dining" },
            { day: 8, title: "Aswan", description: "Philae Temple, felucca sunset sail" },
            { day: 9, title: "Abu Simbel", description: "Private dawn flight to the colossal temples" },
            { day: 10, title: "Departure", description: "Morning at leisure, VIP transfer to airport" },
        ],
        includes: [
            "5-star luxury accommodations",
            "All domestic flights",
            "Private Egyptologist guide",
            "All entrance fees",
            "Luxury Nile cruise",
            "Daily breakfast & select meals",
            "24/7 concierge service",
        ],
        highlights: ["Private pyramid access", "Luxury cruise", "Expert guides", "VIP transfers"],
        maxGroup: 8,
        rating: 5.0,
        reviews: 234,
    },
    {
        id: 2,
        title: "Nile Explorer",
        subtitle: "Classic Egypt Experience",
        days: 7,
        nights: 6,
        price: 1899,
        originalPrice: 2199,
        currency: "EUR",
        level: "Explorer",
        category: "classic",
        description: "The perfect introduction to Egypt's wonders. Explore Cairo's treasures and cruise the legendary Nile in comfort.",
        image: "/images/tours/nile-explorer.jpg",
        timeline: [
            { day: 1, title: "Welcome to Cairo", description: "Airport transfer, evening orientation at hotel" },
            { day: 2, title: "Giza Plateau", description: "Pyramids, Sphinx, and Egyptian Museum" },
            { day: 3, title: "Fly to Aswan", description: "Morning flight, Philae Temple, hotel check-in" },
            { day: 4, title: "Nile Cruise", description: "Sail to Kom Ombo, temple visit at sunset" },
            { day: 5, title: "Edfu to Luxor", description: "Edfu Temple, continue sailing to Luxor" },
            { day: 6, title: "Luxor Treasures", description: "Valley of the Kings, Karnak Temple" },
            { day: 7, title: "Departure", description: "Flight to Cairo, international departure" },
        ],
        includes: [
            "4-star hotels & 5-star cruise",
            "Domestic flights",
            "Professional guide",
            "All entrance fees",
            "Nile cruise with meals",
            "Daily breakfast",
        ],
        highlights: ["Nile cruise", "Major monuments", "Group experience"],
        maxGroup: 16,
        rating: 4.8,
        reviews: 1892,
    },
    {
        id: 3,
        title: "Desert & Oasis",
        subtitle: "Adventure Beyond the Nile",
        days: 5,
        nights: 4,
        price: 1299,
        originalPrice: 1499,
        currency: "EUR",
        level: "Explorer",
        category: "adventure",
        description: "Venture into the Western Desert for an adventure unlike any other. Camp under the stars, swim in ancient springs, and discover hidden temples.",
        image: "/images/tours/desert-oasis.jpg",
        timeline: [
            { day: 1, title: "Cairo to Bahariya", description: "Desert drive, Black Desert exploration" },
            { day: 2, title: "White Desert Camp", description: "Chalk formations, Bedouin dinner, stargazing" },
            { day: 3, title: "Drive to Siwa", description: "Oasis arrival, sunset at salt lake" },
            { day: 4, title: "Siwa Exploration", description: "Oracle Temple, Cleopatra's Spring, Shali Fortress" },
            { day: 5, title: "Return to Cairo", description: "Scenic drive back through the desert" },
        ],
        includes: [
            "4x4 desert vehicles",
            "Desert camping equipment",
            "Oasis hotel",
            "All meals",
            "Experienced desert guide",
            "Entrance fees",
        ],
        highlights: ["Desert camping", "Siwa Oasis", "Off-road adventure"],
        maxGroup: 12,
        rating: 4.9,
        reviews: 567,
    },
    {
        id: 4,
        title: "Time Gate: London → Cairo",
        subtitle: "Premium European Connection",
        days: 8,
        nights: 7,
        price: 2499,
        originalPrice: 2899,
        currency: "GBP",
        level: "Royal",
        category: "timegate",
        description: "Step through the Time Gate from London to ancient Egypt. Premium package includes direct flights, luxury transfers, and curated experiences.",
        image: "/images/tours/timegate-london.jpg",
        timeline: [
            { day: 1, title: "Departure from London", description: "Premium lounge access, direct flight to Cairo" },
            { day: 2, title: "Cairo Immersion", description: "Egyptian Museum, Khan el-Khalili bazaar" },
            { day: 3, title: "Pyramids Experience", description: "Full day at Giza, private Sphinx viewing" },
            { day: 4, title: "Fly to Luxor", description: "East Bank temples, Luxor Temple at night" },
            { day: 5, title: "West Bank Wonders", description: "Valley of the Kings, Hatshepsut Temple" },
            { day: 6, title: "Nile Felucca", description: "Traditional sailing, riverside villages" },
            { day: 7, title: "Luxor at Leisure", description: "Optional hot air balloon, shopping" },
            { day: 8, title: "Return to London", description: "Direct flight home" },
        ],
        includes: [
            "Return flights from London",
            "Premium lounge access",
            "5-star hotels",
            "All transfers",
            "Expert guides",
            "Entrance fees",
            "Daily breakfast",
        ],
        highlights: ["Direct from London", "Premium experience", "Curated itinerary"],
        maxGroup: 10,
        rating: 4.9,
        reviews: 423,
        departureCity: "London",
        departureDates: ["2026-03-15", "2026-04-12", "2026-05-10", "2026-09-20", "2026-10-18"],
    },
    {
        id: 5,
        title: "Time Gate: Paris → Luxor",
        subtitle: "French Connection to Ancient Egypt",
        days: 6,
        nights: 5,
        price: 2299,
        originalPrice: 2699,
        currency: "EUR",
        level: "Royal",
        category: "timegate",
        description: "From the city of lights to the land of pharaohs. A curated journey connecting Paris directly to Luxor's ancient treasures.",
        image: "/images/tours/timegate-paris.jpg",
        timeline: [
            { day: 1, title: "Paris Departure", description: "Charles de Gaulle premium lounge, direct flight" },
            { day: 2, title: "Luxor Arrival", description: "Check-in at Sofitel Winter Palace, orientation" },
            { day: 3, title: "East Bank Temples", description: "Karnak complex, Luxor Temple sunset" },
            { day: 4, title: "West Bank Journey", description: "Valley of Kings & Queens, Medinet Habu" },
            { day: 5, title: "Nile Experience", description: "Luxury dahabiya sail, onboard dinner" },
            { day: 6, title: "Return to Paris", description: "Morning departure" },
        ],
        includes: [
            "Return flights from Paris",
            "5-star Winter Palace hotel",
            "All transfers",
            "Private guide",
            "Entrance fees",
            "Breakfast & select dinners",
        ],
        highlights: ["Direct from Paris", "Winter Palace stay", "Intimate experience"],
        maxGroup: 8,
        rating: 5.0,
        reviews: 189,
        departureCity: "Paris",
        departureDates: ["2026-03-08", "2026-04-05", "2026-05-03", "2026-10-10", "2026-11-07"],
    },
];

export const experiences = [
    {
        id: "explorer",
        name: "Explorer",
        icon: "🧭",
        tagline: "Discover at Your Pace",
        description: "Perfect for curious travelers who want to experience Egypt's highlights with comfort and flexibility.",
        priceMultiplier: 1,
        features: [
            "4-star accommodations",
            "Group tours (max 16)",
            "Professional guides",
            "All major sites",
            "Comfortable transport",
        ],
    },
    {
        id: "royal",
        name: "Royal",
        icon: "👑",
        tagline: "Travel Like a Pharaoh",
        description: "Elevated experiences with luxury accommodations, smaller groups, and exclusive access.",
        priceMultiplier: 1.5,
        features: [
            "5-star luxury hotels",
            "Small groups (max 8)",
            "Expert Egyptologists",
            "VIP site access",
            "Premium transport",
            "Fine dining experiences",
        ],
    },
    {
        id: "pharaoh",
        name: "Pharaoh",
        icon: "𓂀",
        tagline: "Ultimate Private Journey",
        description: "The pinnacle of Egyptian travel. Fully private, completely customizable, utterly unforgettable.",
        priceMultiplier: 2.5,
        features: [
            "Ultra-luxury suites",
            "Fully private tours",
            "Personal Egyptologist",
            "After-hours access",
            "Private jets & yachts",
            "Michelin-star dining",
            "24/7 concierge",
        ],
    },
];

export const testimonials = [
    {
        id: 1,
        name: "Emma Richardson",
        country: "United Kingdom",
        flag: "🇬🇧",
        tour: "Pharaoh's Legacy",
        rating: 5,
        text: "Absolutely magical. Standing inside the Great Pyramid at sunrise, completely alone... I'll never forget it. Goba Travel made the impossible possible.",
        image: "/images/testimonials/emma.jpg",
    },
    {
        id: 2,
        name: "Jean-Pierre Dubois",
        country: "France",
        flag: "🇫🇷",
        tour: "Time Gate: Paris → Luxor",
        rating: 5,
        text: "From Paris to the Pharaohs in hours. The Winter Palace was divine, and our guide was a walking encyclopedia. Magnifique!",
        image: "/images/testimonials/jean.jpg",
    },
    {
        id: 3,
        name: "Hans Mueller",
        country: "Germany",
        flag: "🇩🇪",
        tour: "Desert & Oasis",
        rating: 5,
        text: "Sleeping under the stars in the White Desert was surreal. The Siwa Oasis felt like another planet. A true adventure.",
        image: "/images/testimonials/hans.jpg",
    },
    {
        id: 4,
        name: "Sofia Rossi",
        country: "Italy",
        flag: "🇮🇹",
        tour: "Nile Explorer",
        rating: 5,
        text: "The Nile cruise was the highlight of my year. Watching temples slide by from the deck at sunset... pure cinema.",
        image: "/images/testimonials/sofia.jpg",
    },
];

export const stats = {
    yearsExperience: 15,
    happyTravelers: 50000,
    destinationsCovered: 25,
    averageRating: 4.9,
    countries: ["UK", "France", "Germany", "Italy", "Spain", "Netherlands", "Sweden", "Norway", "Denmark", "Belgium"],
};

export const faqs = [
    {
        question: "What is the best time to visit Egypt?",
        answer: "October to April offers the most comfortable weather, with temperatures between 20-25°C. Summer (May-September) is very hot but less crowded and more affordable.",
    },
    {
        question: "Do I need a visa?",
        answer: "Most European and American visitors can obtain a visa on arrival or apply online for an e-visa. We provide full visa guidance with every booking.",
    },
    {
        question: "Is Egypt safe for tourists?",
        answer: "Yes! Egypt has invested heavily in tourism security. Tourist areas are well-protected, and we maintain the highest safety standards on all our tours.",
    },
    {
        question: "What should I pack?",
        answer: "Light, breathable clothing, comfortable walking shoes, sunscreen, and a hat are essential. We recommend modest attire for temple visits. We provide a detailed packing guide upon booking.",
    },
    {
        question: "Can trips be customized?",
        answer: "Absolutely! Our Pharaoh-level experiences are fully customizable. Even Explorer and Royal packages can be modified. Contact us after booking to discuss options.",
    },
];

export const languages = [
    { code: "en", name: "English", flag: "🇬🇧" },
    { code: "fr", name: "Français", flag: "🇫🇷" },
    { code: "de", name: "Deutsch", flag: "🇩🇪" },
    { code: "it", name: "Italiano", flag: "🇮🇹" },
    { code: "es", name: "Español", flag: "🇪🇸" },
];
