// ========================================
// GOBA TRAVEL - EGYPT TOURISM
// Real tour data from JBR Travel (jbr-travel-eg.com)
// ========================================

// Utility: generate a URL-friendly slug from title
export function generateSlug(title) {
    return title
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-')
        .trim();
}

// Utility: generate availability dates for the next 90 days
// Some random dates are marked unavailable for realism
function generateAvailability() {
    const available = [];
    const unavailable = [];
    const today = new Date();
    for (let i = 1; i <= 90; i++) {
        const date = new Date(today);
        date.setDate(today.getDate() + i);
        const dateStr = date.toISOString().split('T')[0];
        // ~20% of dates are unavailable
        if (Math.random() < 0.2) {
            unavailable.push(dateStr);
        } else {
            available.push(dateStr);
        }
    }
    return { available, unavailable };
}

// Pre-generate availability for each tour (stable per session)
const tourAvailabilities = {};
function getAvailability(tourId) {
    if (!tourAvailabilities[tourId]) {
        tourAvailabilities[tourId] = generateAvailability();
    }
    return tourAvailabilities[tourId];
}

export { getAvailability };

export const destinations = [
    {
        id: 1,
        name: "Giza Pyramids",
        nameAr: "أهرامات الجيزة",
        tagline: "Where Time Began",
        description: "Stand before the last surviving Wonder of the Ancient World. The Great Pyramid has guarded the secrets of the pharaohs for 4,500 years.",
        era: "ancient",
        region: "Giza",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Great Pyramid of Khufu", "Sphinx", "Sound & Light Show", "Camel Rides"],
        rating: 4.9,
        reviews: 12847,
        coordinates: { lat: 29.9792, lng: 31.1342 },
    },
    {
        id: 2,
        name: "Cairo",
        nameAr: "القاهرة",
        tagline: "The City That Never Sleeps",
        description: "Egypt's vibrant capital blends ancient heritage with modern energy. From the Egyptian Museum to Khan El-Khalili bazaar, Cairo pulses with life and history.",
        era: "mixed",
        region: "Cairo",
        image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
        highlights: ["Egyptian Museum", "Khan El-Khalili", "Citadel of Saladin", "Old Cairo"],
        rating: 4.8,
        reviews: 15230,
        coordinates: { lat: 30.0444, lng: 31.2357 },
    },
    {
        id: 3,
        name: "Luxor",
        nameAr: "الأقصر",
        tagline: "The World's Greatest Open-Air Museum",
        description: "Walk through millennia of history in the ancient city of Thebes. Colossal statues and hieroglyph-covered walls tell stories of gods and kings.",
        era: "ancient",
        region: "Luxor",
        image: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
        highlights: ["Valley of the Kings", "Karnak Temple", "Hot Air Balloons", "Luxor Temple"],
        rating: 4.8,
        reviews: 8932,
        coordinates: { lat: 25.6994, lng: 32.6421 },
    },
    {
        id: 4,
        name: "Aswan",
        nameAr: "أسوان",
        tagline: "Gateway to Nubia",
        description: "Where the Nile is at its most beautiful. Aswan offers stunning temples, colorful Nubian villages, and the mighty High Dam — a gateway to Africa.",
        era: "ancient",
        region: "Aswan",
        image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
        highlights: ["Philae Temple", "High Dam", "Unfinished Obelisk", "Nubian Villages"],
        rating: 4.9,
        reviews: 5621,
        coordinates: { lat: 24.0889, lng: 32.8998 },
    },
    {
        id: 5,
        name: "Alexandria",
        nameAr: "الإسكندرية",
        tagline: "Where East Meets West",
        description: "Founded by Alexander the Great, this Mediterranean jewel blends Greek, Roman, and Egyptian heritage with stunning coastal charm and fresh seafood.",
        era: "hellenistic",
        region: "Alexandria",
        image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
        highlights: ["Bibliotheca Alexandrina", "Citadel of Qaitbay", "Catacombs", "Corniche"],
        rating: 4.6,
        reviews: 6234,
        coordinates: { lat: 31.2001, lng: 29.9187 },
    },
    {
        id: 6,
        name: "Siwa Oasis",
        nameAr: "واحة سيوة",
        tagline: "Desert Paradise",
        description: "An otherworldly escape where ancient Berber traditions meet salt lakes, date palms, and the mystical Oracle Temple of Amun.",
        era: "mixed",
        region: "Siwa",
        image: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800&q=80",
        highlights: ["Oracle Temple", "Cleopatra's Pool", "Salt Lakes", "Desert Safari"],
        rating: 4.7,
        reviews: 2187,
        coordinates: { lat: 29.2032, lng: 25.5195 },
    },
    {
        id: 7,
        name: "Fayoum",
        nameAr: "الفيوم",
        tagline: "Egypt's Hidden Oasis",
        description: "Just south of Cairo lies Egypt's secret garden — Fayoum. Ancient waterfalls, desert whales, and serene Lake Qarun await the curious traveler.",
        era: "mixed",
        region: "Fayoum",
        image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80",
        highlights: ["Wadi El Rayan", "Whale Valley", "Lake Qarun", "Tunis Village"],
        rating: 4.5,
        reviews: 1340,
        coordinates: { lat: 29.3084, lng: 30.8428 },
    },

];


// Tour types for filtering
export const tourTypes = [
    { id: 'all', label: 'All Tours' },
    { id: 'full-day', label: 'Full-Day Tour' },
    { id: 'half-day', label: 'Half-Day Tour' },
    { id: 'package', label: 'Packages' },
];


export const tours = [
    // ========== FULL-DAY TOURS ==========
    {
        id: 1,
        slug: "authentic-night-tour-city-of-the-dead-nile-cruise",
        title: "Authentic Night Tour | City of the Dead & Nile Cruise",
        subtitle: "Cairo After Dark",
        tourType: "full-day",
        minPax: 1,
        maxPax: 12,
        days: 1,
        nights: 0,
        price: 85,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Cairo",
        description: "Experience the real Egypt where history meets the present. Walk as a local on Cairo streets, visit the largest open-air museum of Islamic architecture on Muizz Street, stroll Khan El-Khalili bazaar, and explore the mysterious City of the Dead. End your night with a luxurious Nile dinner cruise.",
        image: "https://images.unsplash.com/photo-1553913861-c0a561e721b2?w=800&q=80",
        highlights: ["Muizz Street", "Khan El-Khalili", "City of the Dead", "Cairo Tower", "Nile Dinner Cruise", "Tahrir Square"],
        included: [
            "Hotel pickup and drop off",
            "Entrance fees",
            "Nile dinner cruise",
            "Transportation",
            "Private tour guide",
            "Bottled water",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Extra activities not listed",
            "Professional photo session",
        ],
        itinerary: [
            { time: "4:00 PM", title: "Hotel Pickup", description: "Meet your guide at the hotel lobby" },
            { time: "5:00 PM", title: "City of the Dead", description: "Explore the four-mile-long series of historical cemeteries, a UNESCO World Heritage Site with richly decorated mausoleums and a complete community living among the tombs" },
            { time: "6:30 PM", title: "Muizz Street & Islamic Cairo", description: "Witness medieval Islamic architecture unparalleled in its scale and richness" },
            { time: "7:30 PM", title: "Khan El-Khalili Bazaar", description: "Stroll the vibrant alleyways exploring colorful displays and handmade products" },
            { time: "8:30 PM", title: "Tahrir Square & Cairo Tower", description: "Experience the heart of the city, then enjoy breathtaking panoramic views from the Cairo Tower observation deck" },
            { time: "9:30 PM", title: "Nile Dinner Cruise", description: "Dinner under the stars with a buffet of Egyptian and international cuisine, live music and oriental shows" },
        ],
        rating: 4.9,
        reviews: 234,
    },
    {
        id: 2,
        slug: "old-cairo-garbage-city-tour-unusual-experience",
        title: "Old Cairo & Garbage City Tour | Unusual Experience",
        subtitle: "Hidden Cairo Revealed",
        tourType: "full-day",
        minPax: 1,
        maxPax: 12,
        days: 1,
        nights: 0,
        price: 85,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Cairo",
        description: "Step into the hidden side of Cairo. Visit the iconic Cairo Citadel, explore Coptic Cairo's landmarks, discover the vibrant Khan El-Khalili Bazaar, then experience the extraordinary Garbage City and its stunning Cave Church of St. Simon — the largest church in the Middle East carved into the mountain.",
        image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
        highlights: ["Citadel of Saladin", "Mosque of Mohammed Ali", "Khan El-Khalili", "Coptic Cairo", "Hanging Church", "Cave Church of St. Simon", "Garbage City"],
        included: [
            "Hotel pickup and drop off",
            "Entrance fees",
            "Transportation",
            "Private tour guide",
            "Bottled water",
            "Taxes and service charges",
            "Lunch at a local restaurant",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Extra activities not listed",
            "Professional photo session",
        ],
        itinerary: [
            { time: "8:00 AM", title: "Hotel Pickup", description: "Meet your guide at the hotel" },
            { time: "9:00 AM", title: "Cairo Citadel & Mosque of Mohammed Ali", description: "Experience the grandeur of Islamic architecture and panoramic views of Cairo from the citadel summit" },
            { time: "11:00 AM", title: "Khan El-Khalili Bazaar", description: "The largest bazaar in Africa — explore spices, perfumes, jewelry and handmade crafts" },
            { time: "12:30 PM", title: "Coptic Cairo", description: "Visit the Hanging Church, Church of St. Sergius, and Ben Ezra Synagogue" },
            { time: "2:00 PM", title: "Lunch", description: "Enjoy various dishes from Egyptian cuisine at a local restaurant" },
            { time: "3:00 PM", title: "Garbage City & Cave Church", description: "Discover Manshiyet Nasser and the stunning Cave Church of St. Simon carved into the mountain" },
            { time: "5:00 PM", title: "Drop-off", description: "Transfer back to your hotel" },
        ],
        rating: 4.8,
        reviews: 189,
    },
    {
        id: 3,
        slug: "giza-pyramids-grand-egyptian-museum-tour",
        title: "Giza Pyramids & Grand Egyptian Museum Tour",
        subtitle: "Ancient Wonders & Modern Marvel",
        tourType: "full-day",
        minPax: 1,
        maxPax: 10,
        days: 1,
        nights: 0,
        price: 125,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Giza",
        description: "Stand before the Great Pyramid — one of the Seven Wonders of the Ancient World. See the Pyramid of Khafre, the valley temple, and the renowned Sphinx. Then explore the Grand Egyptian Museum with its colossal pharaoh statues and astonishing galleries showcasing 5,000 years of civilization.",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Great Pyramid of Khufu", "Pyramid of Khafre", "The Great Sphinx", "Valley Temple", "Panoramic View", "Grand Egyptian Museum"],
        included: [
            "Hotel pickup and drop off",
            "Transportation",
            "Entrance fees to the Giza Pyramids",
            "Entrance fees to the Grand Egyptian Museum",
            "Private tour guide",
            "Bottled water",
            "Taxes and service charges",
            "Lunch meal",
        ],
        excluded: [
            "Entrance fees for the interior of the Great Pyramid",
            "Personal expenses",
            "Tipping",
            "Extra activities not listed",
            "Professional photo session",
        ],
        itinerary: [
            { time: "7:00 AM", title: "Hotel Pickup", description: "Picked up in a luxurious air-conditioned vehicle with your expert tour guide" },
            { time: "8:00 AM", title: "The Giza Pyramids", description: "Visit the Great Pyramid of Khufu, the Pyramid of Khafre, the valley temple, and the Great Sphinx" },
            { time: "10:30 AM", title: "Panoramic Viewpoint", description: "Enjoy the breathtaking view of the three pyramids aligned together, take photos, and optional camel rides" },
            { time: "11:30 AM", title: "Lunch", description: "Delicious lunch at a local restaurant" },
            { time: "1:00 PM", title: "Grand Egyptian Museum Tour", description: "3-hour guided tour of the Grand Egyptian Museum — giant pharaoh statues, the main gallery, and thousands of artifacts" },
            { time: "4:00 PM", title: "Drop-off", description: "Transfer back to your hotel" },
        ],
        rating: 5.0,
        reviews: 456,
    },
    {
        id: 4,
        slug: "full-day-giza-pyramids-saqqara-memphis-tour",
        title: "Full-Day Giza Pyramids, Saqqara & Memphis Tour",
        subtitle: "The Complete Ancient Experience",
        tourType: "full-day",
        minPax: 1,
        maxPax: 12,
        days: 1,
        nights: 0,
        price: 140,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Giza",
        description: "An unforgettable day tour to three remarkable ancient sites. Witness the breathtaking Pyramid of Khufu, meet the Sphinx, explore the Giza pyramids complex. Step back to the early pharaonic period at Saqqara with King Djoser's step pyramid, then discover the Memphis open-air museum.",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Giza Pyramids Complex", "Great Pyramid of Khufu", "The Sphinx", "Valley Temple", "Saqqara Step Pyramid", "King Djoser Complex", "Memphis Open-Air Museum"],
        included: [
            "Hotel pickup and drop off",
            "Transfers by private air-conditioned vehicle",
            "Entrance fees",
            "Bottled water",
            "Taxes and service charges",
            "Lunch meal",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Extra activities not listed",
            "Professional photo session",
            "Entry to the interior of the Great Pyramid (optional)",
        ],
        itinerary: [
            { time: "7:00 AM", title: "Hotel Pickup", description: "Early start for the best experience" },
            { time: "8:00 AM", title: "Giza Pyramids Complex", description: "Visit the Great Pyramid, Pyramid of Khafre, the Valley Temple, and the Great Sphinx" },
            { time: "10:30 AM", title: "Panoramic Viewpoint", description: "Breathtaking view of all three pyramids, optional camel rides" },
            { time: "11:30 AM", title: "Saqqara", description: "Explore the funerary complex of King Djoser and the unique Step Pyramid" },
            { time: "1:00 PM", title: "Lunch", description: "Delicious lunch at Saqqara with a variety of Egyptian cuisine" },
            { time: "2:30 PM", title: "Memphis Open-Air Museum", description: "Discover more about ancient Egyptian civilization at this historic site" },
            { time: "4:00 PM", title: "Drop-off", description: "Transfer back to your hotel" },
        ],
        rating: 4.9,
        reviews: 312,
    },
    {
        id: 5,
        slug: "guided-day-tour-pyramids-of-giza-nmec",
        title: "Guided Day Tour: Pyramids of Giza & NMEC",
        subtitle: "Pyramids & Civilization Museum",
        tourType: "full-day",
        minPax: 1,
        maxPax: 10,
        days: 1,
        nights: 0,
        price: 135,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Giza",
        description: "A once-in-a-lifetime experience visiting the Pyramids of Giza — the only remaining Wonder of the Ancient World. After the pyramids, enjoy a guided tour inside the National Museum of Egyptian Civilization (NMEC) in Old Cairo to explore different aspects of 5,000 years of history.",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Great Pyramid of Khufu", "Valley Temple", "The Great Sphinx", "Camel Ride", "Panoramic View", "National Museum of Egyptian Civilization"],
        included: [
            "Hotel pickup and drop off",
            "Transfers by private air-conditioned vehicle",
            "Entrance fees",
            "Bottled water",
            "Taxes and service charges",
            "Lunch meal",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Extra activities not listed",
            "Professional photo session",
        ],
        itinerary: [
            { time: "7:00 AM", title: "Hotel Pickup", description: "Start your once-in-a-lifetime experience" },
            { time: "8:00 AM", title: "Giza Pyramids", description: "Explore the Great Pyramid, Pyramid of Khafre, the Sphinx, and the Valley Temple" },
            { time: "10:30 AM", title: "Panoramic View & Camel Ride", description: "Enjoy the breathtaking panoramic view and an exciting camel ride" },
            { time: "12:00 PM", title: "Lunch", description: "Delicious lunch at an authentic restaurant in Cairo" },
            { time: "1:30 PM", title: "NMEC Tour", description: "Guided tour inside the National Museum of Egyptian Civilization" },
            { time: "4:00 PM", title: "Drop-off", description: "Transfer back to your hotel" },
        ],
        rating: 4.8,
        reviews: 198,
    },
    {
        id: 6,
        slug: "must-do-day-tour-giza-pyramids-saqqara-dahshur",
        title: "Must-Do Day Tour: Giza Pyramids, Saqqara & Dahshur",
        subtitle: "The Triple Pyramid Experience",
        tourType: "full-day",
        minPax: 1,
        maxPax: 12,
        days: 1,
        nights: 0,
        price: 135,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Giza",
        description: "Experience three of Egypt's most iconic pyramid sites in one unforgettable day. From the Great Pyramid of Giza to the ancient Step Pyramid at Saqqara and the remarkable Red and Bent Pyramids at Dahshur — walk in the footsteps of the pharaohs across millennia.",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Giza Pyramids", "The Great Sphinx", "Saqqara Step Pyramid", "Dahshur Red Pyramid", "Dahshur Bent Pyramid", "Panoramic Views"],
        included: [
            "Hotel pickup and drop off",
            "Transfers by private air-conditioned vehicle",
            "Entrance fees",
            "Bottled water",
            "Taxes and service charges",
            "Lunch meal",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Extra activities not listed",
            "Professional photo session",
        ],
        itinerary: [
            { time: "7:00 AM", title: "Hotel Pickup", description: "Start your triple pyramid adventure" },
            { time: "8:00 AM", title: "Giza Pyramids Complex", description: "Visit the Great Pyramid, Sphinx, and panoramic viewpoint" },
            { time: "10:30 AM", title: "Dahshur", description: "Explore the Red Pyramid and the unique Bent Pyramid" },
            { time: "12:30 PM", title: "Lunch", description: "Enjoy a delicious Egyptian meal" },
            { time: "2:00 PM", title: "Saqqara", description: "Visit the Step Pyramid of King Djoser and the funerary complex" },
            { time: "4:00 PM", title: "Drop-off", description: "Transfer back to your hotel" },
        ],
        rating: 4.9,
        reviews: 267,
    },
    {
        id: 7,
        slug: "cairo-must-see-day-tour-citadel-museum-old-cairo",
        title: "Cairo Must-See Day Tour | Citadel, Museum & Old Cairo",
        subtitle: "The Essential Cairo Experience",
        tourType: "full-day",
        minPax: 1,
        maxPax: 12,
        days: 1,
        nights: 0,
        price: 105,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Cairo",
        description: "Explore Cairo's must-see highlights in this best-selling day tour. Begin at the towering Citadel of Saladin with its stunning panoramic views and the breathtaking Mosque of Muhammad Ali. Visit the iconic Old Cairo churches, savor lunch at a floating Nile restaurant, explore the Egyptian Museum in Tahrir, and stroll Khan El-Khalili Bazaar.",
        image: "https://images.unsplash.com/photo-1553913861-c0a561e721b2?w=800&q=80",
        highlights: ["Citadel of Saladin", "Mosque of Muhammad Ali", "Old Cairo Churches", "Hanging Church", "Egyptian Museum", "Khan El-Khalili Bazaar", "Floating Nile Restaurant"],
        included: [
            "Hotel pickup and drop off",
            "Transfers by private air-conditioned vehicle",
            "Entrance fees",
            "Bottled water",
            "Taxes and service charges",
            "Lunch meal",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Extra activities not listed",
            "Professional photo session",
        ],
        itinerary: [
            { time: "8:00 AM", title: "Hotel Pickup", description: "Meet your private guide and start the day" },
            { time: "9:00 AM", title: "Citadel of Saladin", description: "Enjoy stunning panoramic views of Cairo and visit the magnificent Mosque of Muhammad Ali" },
            { time: "10:30 AM", title: "Old Cairo", description: "Visit the Hanging Church, Church of St. Sergius, and Ben Ezra Synagogue" },
            { time: "12:30 PM", title: "Lunch on the Nile", description: "Relax at a magical floating restaurant overlooking the Nile with Egyptian cuisine" },
            { time: "2:00 PM", title: "Egyptian Museum", description: "Private guided tour with your Egyptologist through the treasures of ancient Egypt" },
            { time: "4:00 PM", title: "Khan El-Khalili Bazaar", description: "Stroll through old stores, Egyptian products, and enjoy mint tea at El-Fishawy cafe" },
            { time: "5:30 PM", title: "Drop-off", description: "Transfer back to your hotel" },
        ],
        rating: 4.9,
        reviews: 345,
    },
    {
        id: 8,
        slug: "alexandria-day-tour-from-cairo",
        title: "Alexandria Day Tour from Cairo",
        subtitle: "Mediterranean Pearl in a Day",
        tourType: "full-day",
        minPax: 1,
        maxPax: 15,
        days: 1,
        nights: 0,
        price: 130,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Alexandria",
        description: "An unmissable day trip from Cairo to the city of Alexander the Great. Explore the Alexandria National Museum, see Greco-Roman remains at the Catacombs of Kom El-Shoqafa and Pompey's Pillar, visit the legendary Qaitbey Citadel built where the ancient Lighthouse once stood, and tour the iconic Library of Alexandria.",
        image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
        highlights: ["Alexandria National Museum", "Catacombs of Kom El-Shoqafa", "Pompey's Pillar", "Qaitbey Citadel", "Library of Alexandria", "Corniche Walk"],
        included: [
            "Hotel pickup and drop off",
            "Transfers by private air-conditioned vehicle",
            "Entrance fees",
            "Professional Egyptologist guide",
            "Bottled water",
            "Taxes and service charges",
            "Lunch meal",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Extra activities not listed",
            "Professional photo session",
        ],
        itinerary: [
            { time: "6:30 AM", title: "Hotel Pickup", description: "Early departure from Cairo for the drive to Alexandria" },
            { time: "9:30 AM", title: "Alexandria National Museum", description: "Guided tour through Alexandria's rich history" },
            { time: "11:00 AM", title: "Catacombs & Pompey's Pillar", description: "Explore Greco-Roman remains at the Catacombs of Kom El-Shoqafa and the impressive Serapeum" },
            { time: "12:30 PM", title: "Lunch", description: "Fresh seafood lunch at a local Alexandria restaurant" },
            { time: "2:00 PM", title: "Qaitbey Citadel", description: "Private guided tour inside the citadel, built where the ancient Lighthouse once stood" },
            { time: "3:30 PM", title: "Library of Alexandria", description: "Explore the modern Bibliotheca Alexandrina — culture, history, and art" },
            { time: "4:30 PM", title: "Corniche Walk & Return", description: "Walk along the corniche before the drive back to Cairo" },
        ],
        rating: 4.8,
        reviews: 278,
    },
    {
        id: 9,
        slug: "best-luxor-day-tour-valley-of-the-kings-temples",
        title: "Best Luxor Day Tour | Valley of the Kings & Temples",
        subtitle: "The World's Greatest Open-Air Museum",
        tourType: "full-day",
        minPax: 1,
        maxPax: 10,
        days: 1,
        nights: 0,
        price: 145,
        currency: "USD",
        level: "Royal",
        category: "full-day",
        destination: "Luxor",
        description: "Visit the West Bank of Luxor starting with the Valley of the Kings — where Howard Carter opened King Tutankhamun's tomb to reveal the treasures of the boy king. Explore the vividly painted tombs of Thebes' pharaohs, the Temple of Queen Hatshepsut, and the grand Karnak and Luxor Temples.",
        image: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
        highlights: ["Valley of the Kings", "Temple of Hatshepsut", "Colossi of Memnon", "Karnak Temple", "Luxor Temple"],
        included: [
            "Private Egyptologist guide",
            "Entrance fees to all mentioned sites",
            "Lunch at a local restaurant",
            "All transfers by private air-conditioned vehicle",
            "Hotel or cruise pickup and return",
            "Bottled water",
        ],
        excluded: [
            "Tipping for guide & driver",
            "Any extras not mentioned",
        ],
        itinerary: [
            { time: "7:00 AM", title: "Hotel/Cruise Pickup", description: "Meet your Egyptologist and start the tour" },
            { time: "8:00 AM", title: "Valley of the Kings", description: "Visit 3 royal tombs with vivid paintings depicting burial rites and death rituals of Ancient Egypt" },
            { time: "10:00 AM", title: "Temple of Hatshepsut", description: "Explore El Deir El Bahari — the impressive temple of the only female Pharaoh, rising from the desert in terraces" },
            { time: "11:00 AM", title: "Colossi of Memnon", description: "See the two colossal statues of Amenhotep III on the West Bank" },
            { time: "12:30 PM", title: "Lunch", description: "Traditional Egyptian lunch at a local restaurant" },
            { time: "2:00 PM", title: "Karnak Temple", description: "Explore the largest ancient religious complex in the world" },
            { time: "4:00 PM", title: "Luxor Temple", description: "Visit the stunning temple on the east bank of the Nile" },
            { time: "5:30 PM", title: "Drop-off", description: "Return to your hotel or cruise" },
        ],
        rating: 4.9,
        reviews: 392,
    },
    {
        id: 10,
        slug: "best-aswan-day-tour-philae-temple-dam-obelisk",
        title: "Best Aswan Day Tour | Philae Temple, Dam & Obelisk",
        subtitle: "Nubia's Ancient Treasures",
        tourType: "full-day",
        minPax: 1,
        maxPax: 12,
        days: 1,
        nights: 0,
        price: 110,
        originalPrice: 120,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Aswan",
        description: "Explore three of Aswan's most iconic sites in one day. Walk across the mighty High Dam, take a scenic motorboat ride to the magnificent Philae Temple on Agilkia Island — the ancient temple of Isis saved by UNESCO — and visit the quarry holding the largest known ancient obelisk.",
        image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
        highlights: ["Philae Temple", "Aswan High Dam", "Unfinished Obelisk", "Nile Motorboat Ride", "Lake Nasser", "Temple of Isis"],
        included: [
            "Private Egyptologist guide",
            "Entrance fees to all mentioned sites",
            "Lunch at a traditional restaurant",
            "All transfers by private air-conditioned vehicle",
            "Hotel or cruise pickup and return",
        ],
        excluded: [
            "Tipping for guide & driver",
            "Any extras not mentioned",
        ],
        itinerary: [
            { time: "8:00 AM", title: "Hotel/Cruise Pickup", description: "Start your Aswan day tour" },
            { time: "8:30 AM", title: "Aswan High Dam", description: "Walk across the powerful dam, constructed between 1960 and 1970 to control the Nile floods" },
            { time: "10:00 AM", title: "Philae Temple", description: "Scenic motorboat ride on the Nile to Agilkia Island, then explore the ancient Temple of Isis with its many treasures" },
            { time: "12:30 PM", title: "Lunch", description: "Traditional lunch at a local restaurant" },
            { time: "2:00 PM", title: "Unfinished Obelisk", description: "Visit the quarry holding the largest known ancient obelisk — a third taller than any complete obelisk" },
            { time: "3:30 PM", title: "Drop-off", description: "Return to your hotel or cruise" },
        ],
        rating: 4.8,
        reviews: 215,
    },
    {
        id: 11,
        slug: "aswan-tour-st-simeon-monastery-camel-ride",
        title: "Aswan Tour: St. Simeon Monastery & Camel Ride",
        subtitle: "Desert Monastery Adventure",
        tourType: "full-day",
        minPax: 1,
        maxPax: 8,
        days: 1,
        nights: 0,
        price: 120,
        originalPrice: 135,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Aswan",
        description: "Embark on a unique Aswan adventure combining history and desert exploration. Ride a camel across the golden sands to the ancient Monastery of St. Simeon, one of the largest and best-preserved Coptic monasteries in Egypt, perched on the west bank of the Nile.",
        image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
        highlights: ["St. Simeon Monastery", "Camel Ride", "West Bank", "Desert Landscape", "Nile Views", "Coptic Heritage"],
        included: [
            "Private Egyptologist guide",
            "Entrance fees to all mentioned sites",
            "Camel ride",
            "All transfers by private air-conditioned vehicle",
            "Hotel or cruise pickup and return",
            "Bottled water",
        ],
        excluded: [
            "Tipping for guide & driver",
            "Lunch",
            "Any extras not mentioned",
        ],
        itinerary: [
            { time: "8:00 AM", title: "Hotel/Cruise Pickup", description: "Start your desert monastery adventure" },
            { time: "9:00 AM", title: "West Bank Ferry", description: "Cross to the west bank of the Nile" },
            { time: "9:30 AM", title: "Camel Ride", description: "Ride a camel across the golden desert sands to the monastery" },
            { time: "10:30 AM", title: "St. Simeon Monastery", description: "Explore one of the largest and best-preserved Coptic monasteries in Egypt" },
            { time: "12:30 PM", title: "Drop-off", description: "Return to your hotel or cruise" },
        ],
        rating: 4.7,
        reviews: 143,
    },

    // ========== HALF-DAY TOURS ==========
    {
        id: 12,
        slug: "al-tannoura-egyptian-heritage-dance-show",
        title: "Al Tannoura Egyptian Heritage Dance Show",
        subtitle: "Whirling Colors & Ancient Rhythms",
        tourType: "half-day",
        minPax: 1,
        maxPax: 20,
        days: 0,
        nights: 1,
        price: 20,
        originalPrice: 35,
        currency: "USD",
        level: "Explorer",
        category: "half-day",
        destination: "Cairo",
        description: "Attend the mesmerizing Tannoura show at Wekalet El Ghoury, built in 1504 AD during the Mamelukes reign. Experience the most amazing Egyptian folk musical night performed by El Tanoura Troupe for Cultural Heritage — a troupe that has performed in over 30 countries. Enjoy folkloric music, the colorful Tanoura dance, and spiritual Whirling Dervish performances.",
        image: "https://images.unsplash.com/photo-1553913861-c0a561e721b2?w=800&q=80",
        highlights: ["Tannoura Dance", "Whirling Dervish", "Folkloric Music", "Wekalet El Ghoury", "Cultural Heritage Show"],
        included: [
            "Hotel pickup and return",
            "All transfers by private air-conditioned vehicle",
            "English-speaking escorted representative",
            "Entrance fees to the show",
            "Bottled water",
            "All taxes & service charges",
        ],
        excluded: [
            "Personal expenses",
            "Optional activities",
            "Tipping",
        ],
        itinerary: [
            { time: "6:00 PM", title: "Hotel Pickup", description: "Transfer to Wekalet El Ghoury" },
            { time: "6:15 PM", title: "Entrance", description: "Arrive and take your seats in the historic venue" },
            { time: "7:30 PM", title: "The Show", description: "Folkloric music, Tanoura dance with colorful spinning costumes, and Whirling Dervish performance" },
            { time: "9:00 PM", title: "Drop-off", description: "Transfer back to your hotel" },
        ],
        rating: 4.9,
        reviews: 567,
    },
    {
        id: 13,
        slug: "cairo-nile-dinner-cruise-and-show",
        title: "Cairo Nile Dinner Cruise and Show",
        subtitle: "Dinner Under the Stars",
        tourType: "half-day",
        minPax: 1,
        maxPax: 15,
        days: 0,
        nights: 1,
        price: 60,
        currency: "USD",
        level: "Explorer",
        category: "half-day",
        destination: "Cairo",
        description: "A fabulous way to enjoy a night on the Nile. Dinner on the Nile Maxim cruising restaurant for a two-hour sailing trip with belly dancer, folklore show, oriental music, and a delicious dinner. Delight in the chef's menu along with a selection of Egyptian favourites, made with the freshest ingredients.",
        image: "https://images.unsplash.com/photo-1553913861-c0a561e721b2?w=800&q=80",
        highlights: ["Nile Cruise", "Belly Dance Show", "Oriental Music", "Buffet Dinner", "Cairo Night Views"],
        included: [
            "Hotel pickup and return",
            "All transfers by modern air-conditioned vehicle",
            "Choice of set menu dinner",
            "Belly dancer & oriental show",
            "Western show",
            "All taxes & service charges",
        ],
        excluded: [
            "Any extras not mentioned",
            "Beverages during dinner",
            "Tipping",
        ],
        itinerary: [
            { time: "7:00 PM", title: "Hotel Pickup", description: "Transfer to the Nile cruise boarding point" },
            { time: "8:00 PM", title: "Boarding & Sailing", description: "Board the luxurious cruise ship and begin sailing along the Nile" },
            { time: "8:30 PM", title: "Dinner & Shows", description: "Enjoy a delicious buffet dinner while watching belly dance, oriental music, and folklore performances" },
            { time: "10:00 PM", title: "Drop-off", description: "Transfer back to your hotel" },
        ],
        rating: 4.7,
        reviews: 423,
    },

    // ========== PACKAGES ==========
    {
        id: 14,
        slug: "7-days-best-of-egypt-cairo-nile-cruise",
        title: "7 Days Best of Egypt: Cairo & Nile Cruise",
        subtitle: "The Ultimate Egypt Experience",
        tourType: "package",
        minPax: 2,
        maxPax: 8,
        days: 7,
        nights: 6,
        price: 550,
        originalPrice: 600,
        currency: "USD",
        level: "Royal",
        category: "package",
        destination: "Cairo",
        description: "The complete Egypt experience in 7 unforgettable days. Start in Cairo with the Giza Pyramids, Egyptian Museum, and Khan El-Khalili. Fly to Aswan for a 3-night Nile cruise visiting Philae Temple, Kom Ombo, Edfu, and Luxor's treasures including the Valley of the Kings, Hatshepsut Temple, and Karnak.",
        image: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
        highlights: ["Giza Pyramids", "Egyptian Museum", "Nile Cruise", "Philae Temple", "Kom Ombo", "Edfu Temple", "Valley of the Kings", "Karnak Temple"],
        included: [
            "3 nights full board in Nile cruise",
            "3 nights hotel bed and breakfast in Cairo",
            "Entrance fees to all visits as mentioned",
            "Transportation in private air-conditioned vehicle",
            "English-speaking tour guide in Cairo and on cruise",
            "All transfers as mentioned",
            "Fully private tours in Cairo, small group on cruise",
            "Meet and assist at airport upon arrival and departure",
            "All taxes and services included (no hidden cost)",
            "Domestic flights Cairo-Aswan-Luxor-Cairo",
        ],
        excluded: [
            "Optional excursions not included",
            "Entry visa at airport upon arrival",
            "Beverages and drinks",
            "Tips for guide and driver",
        ],
        itinerary: [
            { time: "Day 1", title: "Arrival in Cairo", description: "Welcome to Cairo! Greeted by representative, assisted through immigration, transferred to hotel" },
            { time: "Day 2", title: "Pyramids, Museum & Bazaar", description: "Visit the Giza Pyramids, explore the Egyptian Museum with 120,000+ artifacts, and shop at Khan El-Khalili Bazaar" },
            { time: "Day 3", title: "Fly to Aswan & Philae Temple", description: "Flight to Aswan, visit Philae Temple by motorboat on the Nile, check into your Nile cruise" },
            { time: "Day 4", title: "Kom Ombo & Edfu Temples", description: "Sail toward Luxor visiting the unique double-temple of Kom Ombo and the best-preserved temple in Egypt at Edfu" },
            { time: "Day 5", title: "Valley of the Kings & Hatshepsut Temple", description: "Explore the West Bank: Colossi of Memnon, Valley of the Kings (3 tombs), and the Temple of Queen Hatshepsut" },
            { time: "Day 6", title: "Karnak & Luxor Temples", description: "Visit the vast Karnak Temple complex and the stunning Luxor Temple on the east bank" },
            { time: "Day 7", title: "Departure", description: "Transfer to Cairo airport for your final departure" },
        ],
        rating: 5.0,
        reviews: 189,
    },
    {
        id: 15,
        slug: "7-days-best-of-egypt-with-sleeper-train",
        title: "7 Days Best of Egypt with Sleeper Train",
        subtitle: "Cairo, Nile Cruise & Sleeper Train Adventure",
        tourType: "package",
        minPax: 2,
        maxPax: 8,
        days: 7,
        nights: 6,
        price: 995,
        originalPrice: 1470,
        currency: "USD",
        level: "Royal",
        category: "package",
        destination: "Cairo",
        description: "The premium Egypt experience combining Cairo's wonders, a sleeper train adventure to Aswan, and a luxurious 3-night Nile cruise. Includes the Giza Pyramids, Egyptian Museum, Philae Temple, Kom Ombo, Edfu, Valley of the Kings, and Karnak — all with private guides and first-class comfort.",
        image: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
        highlights: ["Giza Pyramids", "Egyptian Museum", "Sleeper Train", "Nile Cruise", "Philae Temple", "Valley of the Kings", "Karnak Temple", "Hatshepsut Temple"],
        included: [
            "3 nights full board in Nile cruise",
            "3 nights hotel bed and breakfast in Cairo",
            "Sleeper train tickets Cairo-Aswan",
            "Entrance fees to all visits as mentioned",
            "Transportation in private air-conditioned vehicle",
            "English-speaking tour guide",
            "All transfers as mentioned",
            "Fully private tours in Cairo, small group on cruise",
            "Meet and assist at airport",
            "All taxes and services included (no hidden cost)",
            "Domestic flights Luxor-Cairo",
        ],
        excluded: [
            "Optional excursions not included",
            "Entry visa at airport upon arrival",
            "Beverages and drinks",
            "Tips for guide and driver",
        ],
        itinerary: [
            { time: "Day 1", title: "Arrival in Cairo", description: "Welcome to Cairo! Transfer to hotel for overnight" },
            { time: "Day 2", title: "Pyramids, Museum & Sleeper Train", description: "Full day: Giza Pyramids, the Egyptian Museum, Khan El-Khalili, then transfer to Giza station for sleeper train to Aswan" },
            { time: "Day 3", title: "Aswan & Philae Temple", description: "Arrive Aswan, visit Philae Temple by motorboat, the essential oil factory, then check into Nile cruise" },
            { time: "Day 4", title: "Kom Ombo & Edfu Temples", description: "Sail toward Luxor visiting Kom Ombo temple with its crocodile mummy museum, and Edfu's Temple of Horus by horse carriage" },
            { time: "Day 5", title: "Valley of the Kings & Hatshepsut Temple", description: "West Bank tour: Colossi of Memnon, Valley of the Kings (3 tombs), and the Temple of Queen Hatshepsut" },
            { time: "Day 6", title: "Karnak & Luxor Temples", description: "Explore the vast Karnak complex and Luxor Temple, leisure time on the cruise" },
            { time: "Day 7", title: "Departure", description: "Transfer from Luxor or train station to Cairo airport" },
        ],
        rating: 4.9,
        reviews: 156,
    },
];


// Experience levels
export const experiences = [
    {
        id: "explorer",
        name: "Explorer",
        icon: "🧭",
        tagline: "Discover at Your Pace",
        description: "Perfect for curious travelers who want to experience Egypt's highlights with comfort and flexibility.",
        priceMultiplier: 1,
        features: [
            "Comfortable accommodations",
            "Small group tours",
            "Professional guides",
            "All major sites",
            "Air-conditioned transport",
        ],
    },
    {
        id: "royal",
        name: "Royal",
        icon: "👑",
        tagline: "Travel Like a Pharaoh",
        description: "Elevated experiences with luxury accommodations, private groups, and exclusive access.",
        priceMultiplier: 1.5,
        features: [
            "5-star luxury hotels",
            "Private tours (max 8)",
            "Expert Egyptologists",
            "VIP site access",
            "Premium transport",
            "Fine dining experiences",
        ],
    },
    {
        id: "pharaoh",
        name: "Pharaoh",
        icon: "𓂀",
        tagline: "Ultimate Private Journey",
        description: "The pinnacle of Egyptian travel. Fully private, completely customizable, utterly unforgettable.",
        priceMultiplier: 2.5,
        features: [
            "Ultra-luxury suites",
            "Fully private tours",
            "Personal Egyptologist",
            "After-hours access",
            "Private jets & yachts",
            "Michelin-star dining",
            "24/7 concierge",
        ],
    },
];

export const testimonials = [
    {
        id: 1,
        name: "Sophie",
        country: "Greece",
        flag: "🇬🇷",
        tour: "7 Days Best of Egypt",
        rating: 5,
        text: "If you need hotel or guesthouse suggestions, reach out to Goba Travel — they'll help you find the most suitable and relaxing option near your travel plans, with great value for your budget.",
        image: "/images/testimonials/sophie.jpg",
    },
    {
        id: 2,
        name: "Emma Richardson",
        country: "United Kingdom",
        flag: "🇬🇧",
        tour: "Giza Pyramids & Grand Egyptian Museum",
        rating: 5,
        text: "Absolutely magical. Standing inside the Great Pyramid at sunrise, completely alone... I'll never forget it. The guide was incredibly knowledgeable and made the day unforgettable.",
        image: "/images/testimonials/emma.jpg",
    },
    {
        id: 3,
        name: "Jean-Pierre Dubois",
        country: "France",
        flag: "🇫🇷",
        tour: "7 Days Egypt & Nile Cruise",
        rating: 5,
        text: "From Cairo to the Nile cruise, every moment was perfectly organized. The temples at Luxor were breathtaking and our Egyptologist guide was a walking encyclopedia. Magnifique!",
        image: "/images/testimonials/jean.jpg",
    },
    {
        id: 4,
        name: "Hans Mueller",
        country: "Germany",
        flag: "🇩🇪",
        tour: "Authentic Night Tour",
        rating: 5,
        text: "The night tour of Cairo's City of the Dead was surreal and unique. Ending with a Nile dinner cruise under the stars was the perfect finish. Highly recommended!",
        image: "/images/testimonials/hans.jpg",
    },
    {
        id: 5,
        name: "David Wilson",
        country: "USA",
        flag: "🇺🇸",
        tour: "Pyramids, Saqqara & Dahshur Day Tour",
        rating: 5,
        text: "The transition from our flight to the hotel was seamless. The private tour of the pyramids was the highlight of our 2024. Goba Travel's attention to detail is world-class.",
        image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    },
    {
        id: 6,
        name: "Yuki Tanaka",
        country: "Japan",
        flag: "🇯🇵",
        tour: "7 Days Egypt, Cairo & Nile Cruise",
        rating: 5,
        text: "Everything was perfectly timed. The sleeper train experience was very authentic, and the hot air balloon over Luxor was breathtaking. Very professional service.",
        image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    },
    {
        id: 7,
        name: "Marco Rossi",
        country: "Italy",
        flag: "🇮🇹",
        tour: "Cairo Must See Tour",
        rating: 5,
        text: "L'Egitto è incredibile! Our guide explained the history of the Egyptian Museum with so much passion. Truly an emotionally moving experience.",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    },
    {
        id: 8,
        name: "Sarah Jenkins",
        country: "Australia",
        flag: "🇦🇺",
        tour: "Alexandria Day Tour",
        rating: 5,
        text: "Coming from Sydney, we wanted a stress-free trip. The seafood lunch in Alexandria was incredible, and the library is a modern masterpiece. Highly recommended.",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    },
];

export const stats = {
    yearsExperience: 15,
    happyTravelers: 50000,
    destinationsCovered: 7,
    averageRating: 4.9,
    visitorCountries: ["UK", "France", "Germany", "Italy", "Spain", "Netherlands", "Greece", "USA", "Australia", "Japan"], // where our travelers come from
};

export const faqs = [
    {
        question: "What is the best time to visit Egypt?",
        answer: "October to April offers the most comfortable weather, with temperatures between 20-25°C. Summer (May-September) is very hot but less crowded and more affordable.",
    },
    {
        question: "Do I need a visa?",
        answer: "Most European and American visitors can obtain a visa on arrival or apply online for an e-visa. We provide full visa guidance with every booking.",
    },
    {
        question: "Is Egypt safe for tourists?",
        answer: "Yes! Egypt has invested heavily in tourism security. Tourist areas are well-protected, and we maintain the highest safety standards on all our tours.",
    },
    {
        question: "What should I pack?",
        answer: "Light, breathable clothing, comfortable walking shoes, sunscreen, and a hat are essential. We recommend modest attire for temple visits. We provide a detailed packing guide upon booking.",
    },
    {
        question: "Can trips be customized?",
        answer: "Absolutely! All our packages can be modified to suit your preferences. Contact us to discuss your ideal Egyptian adventure.",
    },
    {
        question: "What is included in the tour price?",
        answer: "Each tour lists exactly what's included and excluded. Generally, all entrance fees, transportation, guide services, and specified meals are included. Tips and personal expenses are excluded.",
    },
    {
        question: "What is the booking and cancellation policy?",
        answer: "A 30% deposit is required to confirm bookings. Rescheduling is available with no extra charges up to 24 hours before the tour date. Full refund if cancelled 24+ hours in advance; 50% charge for late cancellations. Children 0-2 are free, children under 11 get 50% off.",
    },
    {
        question: "What about group sizes?",
        answer: "Most of our day tours are fully private. The 7-day Nile Cruise packages include private tours in Cairo and small group tours on the cruise. We also accommodate solo travelers with a small supplement.",
    },
];

export const languages = [
    { code: "en", name: "English", flag: "🇬🇧" },
    { code: "fr", name: "Français", flag: "🇫🇷" },
    { code: "de", name: "Deutsch", flag: "🇩🇪" },
    { code: "it", name: "Italiano", flag: "🇮🇹" },
    { code: "es", name: "Español", flag: "🇪🇸" },
    { code: "ar", name: "العربية", flag: "🇪🇬" },
];

// Gallery images from JBR Travel client experiences
export const galleryImages = [
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-1.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-2.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-3.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-4.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-5.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-6.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-7.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-8.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-9.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-10.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-11.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-12.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-13.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-14.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-15.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-16.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-17.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-18.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-19.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-20.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-21.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-22.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-23.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-24.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-25.jpg",
    "https://jbr-travel-eg.com/wp-content/uploads/2025/12/gallery-26.jpg",
];
