// ========================================
// GOBA TRAVEL - EGYPT TOURISM
// Real tour data inspired by JBR Travel
// ========================================

export const destinations = [
    {
        id: 1,
        name: "Giza Pyramids",
        nameAr: "أهرامات الجيزة",
        tagline: "Where Time Began",
        description: "Stand before the last surviving Wonder of the Ancient World. The Great Pyramid has guarded the secrets of the pharaohs for 4,500 years.",
        era: "ancient",
        region: "Giza",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Great Pyramid of Khufu", "Sphinx", "Sound & Light Show", "Camel Rides"],
        rating: 4.9,
        reviews: 12847,
        coordinates: { lat: 29.9792, lng: 31.1342 },
    },
    {
        id: 2,
        name: "Cairo",
        nameAr: "القاهرة",
        tagline: "The City That Never Sleeps",
        description: "Egypt's vibrant capital blends ancient heritage with modern energy. From the Egyptian Museum to Khan El-Khalili bazaar, Cairo pulses with life and history.",
        era: "mixed",
        region: "Cairo",
        image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
        highlights: ["Egyptian Museum", "Khan El-Khalili", "Citadel of Saladin", "Old Cairo"],
        rating: 4.8,
        reviews: 15230,
        coordinates: { lat: 30.0444, lng: 31.2357 },
    },
    {
        id: 3,
        name: "Luxor",
        nameAr: "الأقصر",
        tagline: "The World's Greatest Open-Air Museum",
        description: "Walk through millennia of history in the ancient city of Thebes. Colossal statues and hieroglyph-covered walls tell stories of gods and kings.",
        era: "ancient",
        region: "Luxor",
        image: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
        highlights: ["Valley of the Kings", "Karnak Temple", "Hot Air Balloons", "Luxor Temple"],
        rating: 4.8,
        reviews: 8932,
        coordinates: { lat: 25.6994, lng: 32.6421 },
    },
    {
        id: 4,
        name: "Aswan",
        nameAr: "أسوان",
        tagline: "Gateway to Nubia",
        description: "Where the Nile is at its most beautiful. Aswan offers stunning temples, colorful Nubian villages, and the mighty High Dam — a gateway to Africa.",
        era: "ancient",
        region: "Aswan",
        image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
        highlights: ["Philae Temple", "High Dam", "Unfinished Obelisk", "Nubian Villages"],
        rating: 4.9,
        reviews: 5621,
        coordinates: { lat: 24.0889, lng: 32.8998 },
    },
    {
        id: 5,
        name: "Alexandria",
        nameAr: "الإسكندرية",
        tagline: "Where East Meets West",
        description: "Founded by Alexander the Great, this Mediterranean jewel blends Greek, Roman, and Egyptian heritage with stunning coastal charm and fresh seafood.",
        era: "hellenistic",
        region: "Alexandria",
        image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
        highlights: ["Bibliotheca Alexandrina", "Citadel of Qaitbay", "Catacombs", "Corniche"],
        rating: 4.6,
        reviews: 6234,
        coordinates: { lat: 31.2001, lng: 29.9187 },
    },
    {
        id: 6,
        name: "Siwa Oasis",
        nameAr: "واحة سيوة",
        tagline: "Desert Paradise",
        description: "An otherworldly escape where ancient Berber traditions meet salt lakes, date palms, and the mystical Oracle Temple of Amun.",
        era: "mixed",
        region: "Siwa",
        image: "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800&q=80",
        highlights: ["Oracle Temple", "Cleopatra's Pool", "Salt Lakes", "Desert Safari"],
        rating: 4.7,
        reviews: 2187,
        coordinates: { lat: 29.2032, lng: 25.5195 },
    },
    {
        id: 7,
        name: "Fayoum",
        nameAr: "الفيوم",
        tagline: "Egypt's Hidden Oasis",
        description: "Just south of Cairo lies Egypt's secret garden — Fayoum. Ancient waterfalls, desert whales, and serene Lake Qarun await the curious traveler.",
        era: "mixed",
        region: "Fayoum",
        image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80",
        highlights: ["Wadi El Rayan", "Whale Valley", "Lake Qarun", "Tunis Village"],
        rating: 4.5,
        reviews: 1340,
        coordinates: { lat: 29.3084, lng: 30.8428 },
    },
    {
        id: 8,
        name: "Saint Catherine",
        nameAr: "سانت كاترين",
        tagline: "Between Heaven and Earth",
        description: "Home to the sacred Mount Sinai and the world's oldest monastery. Trek to the summit at dawn for a sunrise you'll never forget.",
        era: "ancient",
        region: "Sinai",
        image: "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80",
        highlights: ["Mount Sinai Sunrise", "St. Catherine's Monastery", "Burning Bush", "Bedouin Culture"],
        rating: 4.8,
        reviews: 3450,
        coordinates: { lat: 28.5562, lng: 33.9756 },
    },
];


// Tour types for filtering
export const tourTypes = [
    { id: 'all', label: 'All Tours' },
    { id: 'full-day', label: 'Full-Day Tour' },
    { id: 'half-day', label: 'Half-Day Tour' },
    { id: 'package', label: 'Packages' },
];


export const tours = [
    // ========== FULL-DAY TOURS ==========
    {
        id: 1,
        title: "Authentic Night Tour | City of the Dead & Nile Cruise",
        subtitle: "Cairo After Dark",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 85,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Cairo",
        description: "Experience the real Egypt where history meets the present. Walk as a local on Cairo streets, visit the largest open-air museum of Islamic architecture on Muizz Street, stroll Khan El-Khalili bazaar, and explore the mysterious City of the Dead. End your night with a luxurious Nile dinner cruise.",
        image: "https://images.unsplash.com/photo-1553913861-c0a561e721b2?w=800&q=80",
        highlights: ["Muizz Street", "Khan El-Khalili", "City of the Dead", "Cairo Tower", "Nile Dinner Cruise", "Tahrir Square"],
        included: [
            "Hotel pickup and drop off",
            "Entrance fees",
            "Nile dinner cruise",
            "Transportation",
            "Private tour guide",
            "Bottled water",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Extra activities not listed",
            "Professional photo session",
        ],
        itinerary: [
            { time: "4:00 PM", title: "Hotel Pickup", description: "Meet your guide at the hotel lobby" },
            { time: "5:00 PM", title: "Muizz Street & Islamic Cairo", description: "Explore the largest open-air museum of Islamic architecture" },
            { time: "6:30 PM", title: "Khan El-Khalili Bazaar", description: "Browse the ancient bazaar and feel Egyptian heritage" },
            { time: "8:00 PM", title: "City of the Dead", description: "Walk through the historic cemetery city with stories of the living and the dead" },
            { time: "9:00 PM", title: "Cairo Tower & Nile Corniche", description: "Enjoy panoramic views and a walk along the Nile" },
            { time: "10:00 PM", title: "Nile Dinner Cruise", description: "End the night with dinner and entertainment on the Nile" },
        ],
        rating: 4.9,
        reviews: 234,
    },
    {
        id: 2,
        title: "Old Cairo & Garbage City Tour | Unusual Experience",
        subtitle: "Hidden Cairo Revealed",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 85,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Cairo",
        description: "Discover Cairo's most authentic and unusual corners. Visit the historic Coptic quarter, wander through the vibrant Garbage City with its stunning cave church, and experience the real life of Cairo locals.",
        image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
        highlights: ["Coptic Cairo", "Garbage City", "Cave Church", "Local Markets", "Authentic Street Food"],
        included: [
            "Hotel pickup and drop off",
            "Entrance fees",
            "Transportation",
            "Private tour guide",
            "Bottled water",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Lunch",
        ],
        itinerary: [
            { time: "8:00 AM", title: "Hotel Pickup", description: "Meet your guide at the hotel" },
            { time: "9:00 AM", title: "Coptic Cairo", description: "Visit the Hanging Church, Ben Ezra Synagogue, and Abu Serga Church" },
            { time: "11:30 AM", title: "Garbage City", description: "Explore Manshiyat Naser and the stunning Cave Church of St. Simon" },
            { time: "1:30 PM", title: "Local Lunch", description: "Enjoy authentic Egyptian street food (optional)" },
            { time: "3:00 PM", title: "Old Cairo Streets", description: "Walk through the vibrant streets and markets of historic Cairo" },
        ],
        rating: 4.8,
        reviews: 189,
    },
    {
        id: 3,
        title: "Giza Pyramids & Grand Egyptian Museum Tour",
        subtitle: "Ancient Wonders & Modern Marvel",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 125,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Giza",
        description: "Visit the iconic Giza Pyramids, marvel at the Sphinx, and explore the brand-new Grand Egyptian Museum — the largest archaeological museum in the world housing over 100,000 artifacts including Tutankhamun's treasures.",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Great Pyramids", "The Sphinx", "Grand Egyptian Museum", "Tutankhamun Treasures", "Panoramic View Point"],
        included: [
            "Hotel pickup and drop off",
            "Entrance fees",
            "Grand Egyptian Museum ticket",
            "Transportation",
            "Private Egyptologist guide",
            "Bottled water",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Lunch",
            "Camel ride (optional)",
            "Pyramid interior entry (optional)",
        ],
        itinerary: [
            { time: "7:00 AM", title: "Hotel Pickup", description: "Early start for the best experience" },
            { time: "8:00 AM", title: "Giza Pyramids Complex", description: "Explore the Great Pyramid of Khufu, Khafre, and Menkaure" },
            { time: "9:30 AM", title: "The Great Sphinx", description: "Visit the iconic limestone statue and Valley Temple" },
            { time: "10:30 AM", title: "Panoramic View Point", description: "Photo opportunity with all three pyramids" },
            { time: "12:00 PM", title: "Lunch Break", description: "Lunch at a local restaurant with pyramid views" },
            { time: "1:30 PM", title: "Grand Egyptian Museum", description: "Explore the world's largest archaeological museum" },
            { time: "4:00 PM", title: "Return", description: "Transfer back to your hotel" },
        ],
        rating: 5.0,
        reviews: 456,
    },
    {
        id: 4,
        title: "Full-Day Giza Pyramids, Saqqara & Memphis Tour",
        subtitle: "The Complete Ancient Experience",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 140,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Giza",
        description: "A comprehensive journey through Egypt's ancient capitals. Visit the Giza Pyramids, the Step Pyramid at Saqqara — the world's oldest stone structure — and the ruins of Memphis, Egypt's first capital city.",
        image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
        highlights: ["Giza Pyramids", "Sphinx", "Saqqara Step Pyramid", "Memphis Ruins", "Colossus of Ramesses II"],
        included: [
            "Hotel pickup and drop off",
            "All entrance fees",
            "Air-conditioned vehicle",
            "Private Egyptologist guide",
            "Bottled water",
            "Lunch at local restaurant",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Camel ride (optional)",
            "Pyramid interior entry (optional)",
        ],
        itinerary: [
            { time: "7:00 AM", title: "Hotel Pickup", description: "Start your ancient adventure" },
            { time: "8:00 AM", title: "Giza Plateau", description: "Great Pyramids, Sphinx, and Valley Temple" },
            { time: "11:00 AM", title: "Saqqara Necropolis", description: "Step Pyramid of Djoser and the ancient tombs" },
            { time: "1:00 PM", title: "Lunch", description: "Enjoy local cuisine at a traditional restaurant" },
            { time: "2:30 PM", title: "Memphis Open-Air Museum", description: "The colossal statue of Ramesses II and the Alabaster Sphinx" },
            { time: "4:00 PM", title: "Return", description: "Transfer back to your hotel" },
        ],
        rating: 4.9,
        reviews: 378,
    },
    {
        id: 5,
        title: "Guided Day Tour: Pyramids of Giza & NMEC",
        subtitle: "Pharaohs & Royal Mummies",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 135,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Giza",
        description: "Combine the timeless Giza Pyramids with the National Museum of Egyptian Civilization (NMEC) — home to the Royal Mummies Hall where you can see the actual mummies of Egypt's greatest pharaohs.",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Giza Pyramids", "Sphinx", "NMEC Museum", "Royal Mummies Hall", "Ancient Artifacts"],
        included: [
            "Hotel pickup and drop off",
            "All entrance fees including NMEC",
            "Transportation",
            "Private guide",
            "Bottled water",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Lunch",
            "Royal Mummies Hall extra ticket",
        ],
        itinerary: [
            { time: "7:30 AM", title: "Hotel Pickup", description: "Your guide meets you in the lobby" },
            { time: "8:30 AM", title: "Giza Pyramids", description: "Full tour of the pyramids complex" },
            { time: "11:00 AM", title: "The Sphinx", description: "Visit the iconic Sphinx and photo stop" },
            { time: "12:30 PM", title: "Lunch Break", description: "Local restaurant near the pyramids" },
            { time: "2:00 PM", title: "NMEC Museum", description: "Explore Egyptian civilization from prehistoric to modern times" },
            { time: "4:30 PM", title: "Return", description: "Drop off at your hotel" },
        ],
        rating: 4.8,
        reviews: 267,
    },
    {
        id: 6,
        title: "Pyramids, Saqqara & Dahshur Day Tour",
        subtitle: "The Pyramid Evolution",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 135,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Giza",
        description: "Witness the evolution of pyramid building across three incredible sites. From the Bent and Red Pyramids at Dahshur, to the Step Pyramid at Saqqara, to the perfected Great Pyramids of Giza — see how the pharaohs mastered their craft.",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Bent Pyramid", "Red Pyramid", "Step Pyramid", "Giza Pyramids", "Sphinx"],
        included: [
            "Hotel pickup and drop off",
            "All entrance fees",
            "Air-conditioned vehicle",
            "Egyptologist guide",
            "Bottled water",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Lunch",
        ],
        itinerary: [
            { time: "7:00 AM", title: "Hotel Pickup", description: "Early departure for a full day of exploration" },
            { time: "8:00 AM", title: "Dahshur", description: "Visit the Bent Pyramid and enter the Red Pyramid" },
            { time: "10:30 AM", title: "Saqqara", description: "The Step Pyramid complex and Serapeum" },
            { time: "1:00 PM", title: "Lunch", description: "Local restaurant break" },
            { time: "2:30 PM", title: "Giza Pyramids & Sphinx", description: "The grand finale — the Great Pyramids" },
            { time: "5:00 PM", title: "Return", description: "Drop off at your hotel" },
        ],
        rating: 4.9,
        reviews: 312,
    },
    {
        id: 7,
        title: "Best Aswan Day Tour: Philae Temple, High Dam & Obelisk",
        subtitle: "Nubian Heritage Explorer",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 110,
        originalPrice: 120,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Aswan",
        description: "Discover Aswan's finest treasures. Cross the Nile by motorboat to the beautiful Philae Temple dedicated to Goddess Isis, marvel at the engineering feat of the Aswan High Dam, and visit the Unfinished Obelisk — the largest known ancient obelisk.",
        image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
        highlights: ["Philae Temple", "Aswan High Dam", "Unfinished Obelisk", "Motorboat Ride", "Essential Oil Factory"],
        included: [
            "Hotel pickup and drop off",
            "All entrance fees",
            "Motorboat to Philae Temple",
            "Air-conditioned vehicle",
            "Private tour guide",
            "Bottled water",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Lunch",
        ],
        itinerary: [
            { time: "8:00 AM", title: "Hotel Pickup", description: "Meet your guide in Aswan" },
            { time: "8:30 AM", title: "Aswan High Dam", description: "Visit the impressive engineering marvel" },
            { time: "9:30 AM", title: "Unfinished Obelisk", description: "See the largest known ancient obelisk" },
            { time: "11:00 AM", title: "Philae Temple", description: "Motorboat to the island temple of Goddess Isis" },
            { time: "1:00 PM", title: "Essential Oil Factory", description: "Learn about traditional Egyptian perfumes" },
            { time: "2:00 PM", title: "Return", description: "Transfer back to your hotel" },
        ],
        rating: 4.8,
        reviews: 198,
    },
    {
        id: 8,
        title: "Best Luxor Day Tour: Valley of Kings, Karnak & Luxor Temple",
        subtitle: "Thebes Unveiled",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 145,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Luxor",
        description: "Explore both banks of the Nile in Luxor. Visit the legendary Valley of the Kings, the Temple of Queen Hatshepsut, the Colossi of Memnon on the West Bank, then cross to the East Bank for the magnificent Karnak and Luxor Temples.",
        image: "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80",
        highlights: ["Valley of the Kings", "Hatshepsut Temple", "Colossi of Memnon", "Karnak Temple", "Luxor Temple"],
        included: [
            "Hotel pickup and drop off",
            "All entrance fees (3 tombs in Valley of Kings)",
            "Air-conditioned vehicle",
            "Private Egyptologist guide",
            "Bottled water",
            "Lunch at local restaurant",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Tutankhamun tomb extra ticket",
            "Photography tickets inside tombs",
        ],
        itinerary: [
            { time: "7:00 AM", title: "Hotel Pickup", description: "Early start to beat the heat" },
            { time: "7:30 AM", title: "Valley of the Kings", description: "Visit 3 royal tombs carved deep into the rock" },
            { time: "9:30 AM", title: "Hatshepsut Temple", description: "The terraced temple of Egypt's only female pharaoh" },
            { time: "10:30 AM", title: "Colossi of Memnon", description: "The twin statues of Amenhotep III" },
            { time: "11:30 AM", title: "Lunch", description: "Local restaurant in Luxor" },
            { time: "1:00 PM", title: "Karnak Temple", description: "The largest ancient religious complex in the world" },
            { time: "3:00 PM", title: "Luxor Temple", description: "The stunning temple in the heart of the city" },
            { time: "4:30 PM", title: "Return", description: "Transfer back to your hotel" },
        ],
        rating: 5.0,
        reviews: 445,
    },
    {
        id: 9,
        title: "Alexandria Day Tour from Cairo",
        subtitle: "Mediterranean Escape",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 105,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Alexandria",
        description: "Escape to Egypt's Mediterranean coast for a day. Explore the stunning Bibliotheca Alexandrina, the medieval Citadel of Qaitbay, the eerie Catacombs of Kom El Shoqafa, and enjoy fresh seafood by the sea.",
        image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80",
        highlights: ["Bibliotheca Alexandrina", "Citadel of Qaitbay", "Catacombs", "Pompey's Pillar", "Seafood Lunch"],
        included: [
            "Hotel pickup and drop off in Cairo",
            "All entrance fees",
            "Air-conditioned vehicle",
            "Private tour guide",
            "Bottled water",
            "Seafood lunch",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
        ],
        itinerary: [
            { time: "6:00 AM", title: "Cairo Pickup", description: "Early departure from your Cairo hotel" },
            { time: "9:00 AM", title: "Catacombs of Kom El Shoqafa", description: "Explore the Roman-era underground burial site" },
            { time: "10:30 AM", title: "Pompey's Pillar", description: "The tallest ancient monument in Alexandria" },
            { time: "11:30 AM", title: "Citadel of Qaitbay", description: "Medieval fortress on the Mediterranean coast" },
            { time: "1:00 PM", title: "Seafood Lunch", description: "Fresh catch at a seaside restaurant" },
            { time: "2:30 PM", title: "Bibliotheca Alexandrina", description: "The modern library honoring the ancient wonder" },
            { time: "4:00 PM", title: "Return to Cairo", description: "Scenic drive back to Cairo" },
        ],
        rating: 4.7,
        reviews: 289,
    },
    {
        id: 10,
        title: "Cairo Must-See: Citadel, Egyptian Museum & Old Cairo",
        subtitle: "Essential Cairo Highlights",
        tourType: "full-day",
        days: 1,
        nights: 0,
        price: 130,
        currency: "USD",
        level: "Explorer",
        category: "full-day",
        destination: "Cairo",
        description: "Hit all of Cairo's must-see landmarks in one packed day. Visit the iconic Egyptian Museum with its Tutankhamun treasures, the majestic Citadel of Saladin with the Alabaster Mosque, and explore the historic streets of Coptic and Islamic Old Cairo.",
        image: "https://images.unsplash.com/photo-1553913861-c0a561e721b2?w=800&q=80",
        highlights: ["Egyptian Museum", "Citadel of Saladin", "Alabaster Mosque", "Coptic Cairo", "Islamic Cairo"],
        included: [
            "Hotel pickup and drop off",
            "All entrance fees",
            "Air-conditioned vehicle",
            "Private Egyptologist guide",
            "Lunch at local restaurant",
            "Bottled water",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Royal Mummies Hall extra ticket",
        ],
        itinerary: [
            { time: "8:00 AM", title: "Hotel Pickup", description: "Start your Cairo discovery" },
            { time: "9:00 AM", title: "Egyptian Museum", description: "5,000 years of art including Tutankhamun's gold" },
            { time: "11:30 AM", title: "Citadel of Saladin", description: "The Alabaster Mosque and panoramic Cairo views" },
            { time: "1:00 PM", title: "Lunch", description: "Traditional Egyptian meal at a local restaurant" },
            { time: "2:30 PM", title: "Old Cairo", description: "Hanging Church, Ben Ezra Synagogue, and historic streets" },
            { time: "4:30 PM", title: "Return", description: "Transfer back to your hotel" },
        ],
        rating: 4.8,
        reviews: 367,
    },

    // ========== HALF-DAY TOURS ==========
    {
        id: 11,
        title: "Cairo Nile Dinner Cruise & Show",
        subtitle: "Evening on the Nile",
        tourType: "half-day",
        days: 0,
        nights: 1,
        price: 60,
        currency: "USD",
        level: "Explorer",
        category: "half-day",
        destination: "Cairo",
        description: "Enjoy a magical evening cruising the Nile River through illuminated Cairo. Savor an international buffet dinner while watching traditional belly dancing, Tanoura spinning, and live Oriental music under the stars.",
        image: "https://images.unsplash.com/photo-1553913861-c0a561e721b2?w=800&q=80",
        highlights: ["Nile Cruise", "Buffet Dinner", "Belly Dancing", "Tanoura Show", "Live Music"],
        included: [
            "Hotel pickup and drop off",
            "2-hour Nile cruise",
            "Open buffet dinner",
            "Entertainment shows",
            "Transportation",
            "Taxes and service charges",
        ],
        excluded: [
            "Personal expenses",
            "Tipping",
            "Beverages and drinks",
        ],
        itinerary: [
            { time: "6:30 PM", title: "Hotel Pickup", description: "Transfer to the cruise dock" },
            { time: "7:30 PM", title: "Board the Cruise", description: "Welcome drink and settle in" },
            { time: "8:00 PM", title: "Dinner & Shows", description: "Buffet dinner with belly dancing, Tanoura, and live music" },
            { time: "10:00 PM", title: "Return", description: "Transfer back to your hotel" },
        ],
        rating: 4.6,
        reviews: 523,
    },

    // ========== PACKAGES ==========
    {
        id: 12,
        title: "7 Days Best of Egypt: Cairo & Nile Cruise",
        subtitle: "The Complete Egyptian Odyssey",
        tourType: "package",
        days: 7,
        nights: 6,
        price: 550,
        originalPrice: 600,
        currency: "USD",
        level: "Royal",
        category: "package",
        destination: "Cairo, Luxor, Aswan",
        description: "The perfect introduction to Egypt's greatest treasures. Explore Cairo's Pyramids and the Egyptian Museum, then fly to Aswan for a 3-night Nile cruise visiting Philae Temple, Kom Ombo, Edfu, and the Valley of the Kings in Luxor.",
        image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=800&q=80",
        highlights: ["Giza Pyramids", "Egyptian Museum", "Nile Cruise", "Philae Temple", "Valley of the Kings", "Karnak Temple"],
        included: [
            "3 nights hotel (B&B) in Cairo",
            "3 nights full board on Nile cruise",
            "Domestic flights (Cairo–Aswan, Luxor–Cairo)",
            "All entrance fees",
            "Private air-conditioned vehicle",
            "English-speaking tour guide",
            "All transfers",
            "Meet and assist at airport",
            "All taxes and services (no hidden costs)",
        ],
        excluded: [
            "Optional excursions",
            "Entry visa",
            "Beverages and drinks",
            "Tips for guide and driver",
        ],
        itinerary: [
            { day: 1, title: "Arrival in Cairo", description: "Welcome at airport, transfer to hotel. Overnight in Cairo." },
            { day: 2, title: "Pyramids, Museum & Khan El-Khalili", description: "Visit Giza Pyramids, Sphinx, Egyptian Museum, and the famous bazaar. Evening sleeper train to Aswan." },
            { day: 3, title: "Aswan – Philae Temple & Nile Cruise", description: "Arrive in Aswan, visit Philae Temple by motorboat, board your Nile cruise." },
            { day: 4, title: "Kom Ombo & Edfu Temples", description: "Sail the Nile visiting the dual temple of Kom Ombo and the falcon temple at Edfu." },
            { day: 5, title: "Valley of the Kings & Luxor Temples", description: "Explore the Valley of the Kings, Hatshepsut Temple, Colossi of Memnon, and Karnak Temple." },
            { day: 6, title: "Luxor at Leisure", description: "Free day to explore Luxor or take an optional hot air balloon ride at sunrise." },
            { day: 7, title: "Departure", description: "Transfer to airport for your final departure." },
        ],
        maxGroup: 16,
        rating: 4.9,
        reviews: 892,
    },
    {
        id: 13,
        title: "7 Days Egypt, Cairo & Nile Cruise with Sleeper Train",
        subtitle: "Premium Egyptian Adventure",
        tourType: "package",
        days: 7,
        nights: 6,
        price: 995,
        originalPrice: 1470,
        currency: "USD",
        level: "Royal",
        category: "package",
        destination: "Cairo, Luxor, Aswan",
        description: "Experience the best of Egypt in ultimate comfort. From private pyramid access to luxury Nile cruises, this premium package includes domestic flights, sleeper train experience, and guided tours of every major landmark.",
        image: "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=800&q=80",
        highlights: ["Private Pyramid Access", "Luxury Nile Cruise", "Sleeper Train", "All Major Temples", "Expert Egyptologist"],
        included: [
            "3 nights full board on Nile cruise",
            "3 nights hotel (B&B) in Cairo",
            "All entrance fees as mentioned",
            "Transportation in private air-conditioned vehicle",
            "English-speaking tour guide in Cairo and on cruise",
            "All transfers",
            "Fully private tours in Cairo, small group on cruise",
            "Meet and assist at airport",
            "All taxes and services (no hidden costs)",
            "Domestic flights (Cairo–Aswan–Luxor–Cairo)",
        ],
        excluded: [
            "Optional excursions",
            "Entry visa at airport",
            "Beverages and drinks",
            "Tips for guide and driver",
        ],
        itinerary: [
            { day: 1, title: "Arrival in Cairo", description: "VIP airport greeting, transfer to hotel. Overnight in Cairo." },
            { day: 2, title: "Pyramids, Museum & Bazaar / Sleeper Train", description: "Full day: Giza Pyramids, Sphinx, Egyptian Museum with Tutankhamun's treasures, Khan El-Khalili bazaar. Evening sleeper train to Aswan." },
            { day: 3, title: "Aswan – Philae Temple & Nile Cruise", description: "Arrive in Aswan, visit Philae Temple via motorboat, essential oil factory. Board your luxury Nile cruise for 3 nights." },
            { day: 4, title: "Sailing: Kom Ombo & Edfu", description: "Cruise to Kom Ombo — dual temple of Sobek & Horus, see crocodile mummies. Continue to Edfu by horse carriage to explore the best-preserved temple in Egypt." },
            { day: 5, title: "Valley of the Kings, Hatshepsut & Karnak", description: "West Bank: Valley of the Kings (3 tombs), Hatshepsut Temple, Colossi of Memnon. East Bank: magnificent Karnak Temple complex." },
            { day: 6, title: "Luxor Free Day / Optional Hot Air Balloon", description: "Morning at leisure. Optional sunrise hot air balloon over Luxor's west bank. Afternoon free to explore." },
            { day: 7, title: "Final Departure", description: "Transfer to Luxor or Cairo airport for your flight home." },
        ],
        maxGroup: 8,
        rating: 5.0,
        reviews: 423,
    },
];


export const experiences = [
    {
        id: "explorer",
        name: "Explorer",
        icon: "🧭",
        tagline: "Discover at Your Pace",
        description: "Perfect for curious travelers who want to experience Egypt's highlights with comfort and flexibility.",
        priceMultiplier: 1,
        features: [
            "Comfortable accommodations",
            "Small group tours",
            "Professional guides",
            "All major sites",
            "Air-conditioned transport",
        ],
    },
    {
        id: "royal",
        name: "Royal",
        icon: "👑",
        tagline: "Travel Like a Pharaoh",
        description: "Elevated experiences with luxury accommodations, private groups, and exclusive access.",
        priceMultiplier: 1.5,
        features: [
            "5-star luxury hotels",
            "Private tours (max 8)",
            "Expert Egyptologists",
            "VIP site access",
            "Premium transport",
            "Fine dining experiences",
        ],
    },
    {
        id: "pharaoh",
        name: "Pharaoh",
        icon: "𓂀",
        tagline: "Ultimate Private Journey",
        description: "The pinnacle of Egyptian travel. Fully private, completely customizable, utterly unforgettable.",
        priceMultiplier: 2.5,
        features: [
            "Ultra-luxury suites",
            "Fully private tours",
            "Personal Egyptologist",
            "After-hours access",
            "Private jets & yachts",
            "Michelin-star dining",
            "24/7 concierge",
        ],
    },
];

export const testimonials = [
    {
        id: 1,
        name: "Sophie",
        country: "Greece",
        flag: "🇬🇷",
        tour: "7 Days Best of Egypt",
        rating: 5,
        text: "If you need hotel or guesthouse suggestions, reach out to Goba Travel — they'll help you find the most suitable and relaxing option near your travel plans, with great value for your budget.",
        image: "/images/testimonials/sophie.jpg",
    },
    {
        id: 2,
        name: "Emma Richardson",
        country: "United Kingdom",
        flag: "🇬🇧",
        tour: "Giza Pyramids & Grand Egyptian Museum",
        rating: 5,
        text: "Absolutely magical. Standing inside the Great Pyramid at sunrise, completely alone... I'll never forget it. The guide was incredibly knowledgeable and made the day unforgettable.",
        image: "/images/testimonials/emma.jpg",
    },
    {
        id: 3,
        name: "Jean-Pierre Dubois",
        country: "France",
        flag: "🇫🇷",
        tour: "7 Days Egypt & Nile Cruise",
        rating: 5,
        text: "From Cairo to the Nile cruise, every moment was perfectly organized. The temples at Luxor were breathtaking and our Egyptologist guide was a walking encyclopedia. Magnifique!",
        image: "/images/testimonials/jean.jpg",
    },
    {
        id: 4,
        name: "Hans Mueller",
        country: "Germany",
        flag: "🇩🇪",
        tour: "Authentic Night Tour",
        rating: 5,
        text: "The night tour of Cairo's City of the Dead was surreal and unique. Ending with a Nile dinner cruise under the stars was the perfect finish. Highly recommended!",
        image: "/images/testimonials/hans.jpg",
    },
    {
        id: 5,
        name: "David Wilson",
        country: "USA",
        flag: "🇺🇸",
        tour: "Pyramids, Saqqara & Dahshur Day Tour",
        rating: 5,
        text: "The transition from our flight to the hotel was seamless. The private tour of the pyramids was the highlight of our 2024. Goba Travel's attention to detail is world-class.",
        image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    },
    {
        id: 6,
        name: "Yuki Tanaka",
        country: "Japan",
        flag: "🇯🇵",
        tour: "7 Days Egypt, Cairo & Nile Cruise",
        rating: 5,
        text: "Everything was perfectly timed. The sleeper train experience was very authentic, and the hot air balloon over Luxor was breathtaking. Very professional service.",
        image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    },
    {
        id: 7,
        name: "Marco Rossi",
        country: "Italy",
        flag: "🇮🇹",
        tour: "Cairo Must See Tour",
        rating: 5,
        text: "L'Egitto è incredibile! Our guide explained the history of the Egyptian Museum with so much passion. Truly an emotionally moving experience.",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    },
    {
        id: 8,
        name: "Sarah Jenkins",
        country: "Australia",
        flag: "🇦🇺",
        tour: "Alexandria Day Tour",
        rating: 5,
        text: "Coming from Sydney, we wanted a stress-free trip. The seafood lunch in Alexandria was incredible, and the library is a modern masterpiece. Highly recommended.",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
    },
];

export const stats = {
    yearsExperience: 15,
    happyTravelers: 50000,
    destinationsCovered: 8,
    averageRating: 4.9,
    countries: ["UK", "France", "Germany", "Italy", "Spain", "Netherlands", "Greece", "USA", "Australia", "Japan"],
};

export const faqs = [
    {
        question: "What is the best time to visit Egypt?",
        answer: "October to April offers the most comfortable weather, with temperatures between 20-25°C. Summer (May-September) is very hot but less crowded and more affordable.",
    },
    {
        question: "Do I need a visa?",
        answer: "Most European and American visitors can obtain a visa on arrival or apply online for an e-visa. We provide full visa guidance with every booking.",
    },
    {
        question: "Is Egypt safe for tourists?",
        answer: "Yes! Egypt has invested heavily in tourism security. Tourist areas are well-protected, and we maintain the highest safety standards on all our tours.",
    },
    {
        question: "What should I pack?",
        answer: "Light, breathable clothing, comfortable walking shoes, sunscreen, and a hat are essential. We recommend modest attire for temple visits. We provide a detailed packing guide upon booking.",
    },
    {
        question: "Can trips be customized?",
        answer: "Absolutely! All our packages can be modified to suit your preferences. Contact us to discuss your ideal Egyptian adventure.",
    },
    {
        question: "What is included in the tour price?",
        answer: "Each tour lists exactly what's included and excluded. Generally, all entrance fees, transportation, guide services, and specified meals are included. Tips and personal expenses are excluded.",
    },
];

export const languages = [
    { code: "en", name: "English", flag: "🇬🇧" },
    { code: "fr", name: "Français", flag: "🇫🇷" },
    { code: "de", name: "Deutsch", flag: "🇩🇪" },
    { code: "it", name: "Italiano", flag: "🇮🇹" },
    { code: "es", name: "Español", flag: "🇪🇸" },
    { code: "ar", name: "العربية", flag: "🇪🇬" },
];

// Gallery images for "Our Clients' Experiences" section
export const galleryImages = [
    "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=400&q=80",
    "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=400&q=80",
    "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=400&q=80",
    "https://images.unsplash.com/photo-1553913861-c0a561e721b2?w=400&q=80",
    "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=400&q=80",
    "https://images.unsplash.com/photo-1547234935-80c7145ec969?w=400&q=80",
    "https://images.unsplash.com/photo-1548013146-72479768bada?w=400&q=80",
    "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&q=80",
];
